---
title: "Practical C"
author: "Statistical Programming with R"
date: ""
output: html_document

---
#### Exercises
In this exercise we will learn to use packages and write data to/from external sources

---

1. **Install the package called `RSQLite` using the console and skim the console-output.** 

---

2. **Load the package `dplyr` and read the output in the console. What do you think it means?**

---

3. **Open the vignette for the package `DBI`. If you do not have it installed, do so. This might come in handy later**

---

4. **Together with 3-4 colleagues make a data frame with three columns. One column should be a character column with your names. The second column should be a numeric column with your shoe size. The third column should be a logical column with `TRUE` if you have used `R` before and `FALSE` if you have not. Assign the data frame to a name you choose yourselves**

---

5. **Write your data frame to an excel-file (.xlsx).**

----

6. **Open your file in Excel and edit a value. Save it and load it back into R. Does it look like you expected?**

---

7. **Open a connection to a SQLite database on the shared drive and give it a unique name.** Warning: Be sure not to overwrite each others databases. Give it a name that makes it clear it is yours.

---

8. **Write the data set to your database using the functions from the lecture. Check that there is actually create a table in the database.**

---

9. **Read the data set from the database back into R and inspect it. Does it look like you expected?** 

---

10. **Disconnect from your database**

---

11. **Ask another group for the path to their database and open a connection to it. Use this connection to show the name of their table.** If this is not possible, download this extra database from the website [here](files/daltons.sqlite)

---

12. **Append your own data set to the other groups table. Appending is when you add your data the existing data. Read the help-file for `dbWriteTable` to see how it is done. Close the connection when you are done.**

---

13. **Reopen the connection to your own database and read your table. Can you see the new data that has been added?**

---

14. **If you have more time, try making an SQL-query to select only the data where shoe size is greater than 40**

---
End of practical
